services:

  # Backend service - run the FastAPI backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: perishless-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./perishless-3c73c-firebase-adminsdk-fbsvc-17d12425cf.json:/app/firebase.json:ro
    environment:
      GOOGLE_CLOUD_CONNECTION_STIRNG: "perishless-3c73c:us-central1:free-trial-first-project"
      GEMINI_API_KEY: "AIzaSyD9R-LL-ZZgMmuhoKTGZihnN1OxT2hr1ww"
      YOUTUBE_API_KEY: "AIzaSyDWoU5uk9kE3bn65Whe2eYtoKkTxIk-duc"
      GOOGLE_CLOUD_USERNAME: "free-trial-first-project"
      GOOGLE_CLOUD_PASSWORD: "fzmbzF@9NiQ>LT"
      PEXELS_API_KEY: "s7sOHydhPoMnKdF5qIWunAvJT5xSCl81NiBjIq9hql9uGgCtdbC9JuIy"
      DB_USER: "free-trial-first-project"
      DB_PASSWORD: "fzmbzF@9NiQ>LT"
      DB_NAME: "products"
      DB_HOST: "127.0.0.1"
      DB_PORT: "3306"
      GOOGLE_APPLICATION_CREDENTIALS: "/home/jj/repos/Perishless/backend/perishless-3c73c-firebase-adminsdk-fbsvc-17d12425cf.json"
      ELEVEN_LABS_API_KEY: "sk_99f19c4715d9e58feccdba56fbe7f5e7b71179402e78e646"
      

  # Frontend service - run the React frontend with nginx serving the built files
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: perishless-frontend
    restart: always
    ports:
      - "3000:80"